# Generated by Django 4.2.4 on 2023-08-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=120)),
                ('ingredients', models.TextField()),
                ('cooking_time', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
